Discord provider: update to use new links
hapijs/bell pull request #478
Opened 2021-05-17 15:27 UTC by RDIL

Discord said they would drop support for the `discordapp.com` domain sometime soon in favor of the `discord.com` domain.  This updates the links to avoid it from breaking users' code out of the blue.

2021-07-02 15:52 UTC, Nargonath approved these changes
I agree with the changes. Discord documentation seems to show the `discord.com` URLs: https://discord.com/developers/docs/topics/oauth2#shared-resources-oauth2-urls.

2021-07-02 15:54 UTC, Nargonath requested changes
I just noticed that the tests needs to be updated too: https://github.com/hapijs/bell/blob/master/test/providers/discord.js

2021-07-03 02:55 UTC, RDIL commented
Fixed!

2021-07-03 12:03 UTC, Nargonath commented
@RDIL Are you sure you didn't forget to push because I cannot see any changes to the test here?

2021-07-03 15:04 UTC, RDIL commented
@Nargonath I did it on the wrong branch!  Sorry.

2021-07-05 18:20 UTC, Nargonath requested changes
There are still some occurrences of `discordapp` throughout the project that need to be updated too IMO:

![image](https://user-images.githubusercontent.com/583657/124507532-3eb54280-ddce-11eb-82dc-dc9ad2c91013.png)

Most of them are documentations/dummy data but there is one left in `lib/providers/discord.js`. I don't know if it's a drop-in replacement with `cdn.discord.com`.

2021-07-05 18:30 UTC, RDIL commented
> No problem @RDIL, it happens. 😄
> 
> There are still some occurrences of `discordapp` throughout the project that need to be updated too IMO:
> 
> ![image](https://user-images.githubusercontent.com/583657/124507532-3eb54280-ddce-11eb-82dc-dc9ad2c91013.png)
> 
> Most of them are documentations/dummy data but there is one left in `lib/providers/discord.js`. I don't know if it's a drop-in replacement with `cdn.discord.com`.

Good catches in the docs.  Discord has however said that the CDN is staying for cache purposes. Will fix when I get back home.

2021-07-05 18:57 UTC, Nargonath commented
Alright, thank you @RDIL.

2021-07-07 08:26 UTC, Nargonath approved these changes
LGTM, thanks @RDIL for the contribution. 👍

2021-07-12 20:58 UTC, merged